In [1]:
from keras.models import Sequential,load_model
from keras.layers import Dense, Flatten, Conv1D, Reshape
import numpy as np

In [2]:
config = {
    'discount': 0.95,
    'exploration_rate':0.9,
    'decay_factor':0.99,
    'learning_rate':0.001,
    'episode':100,
    'debug' : 0,
    'chances' : 12,
    'digits' : 4,
    'peg_count': 6,
    'mode' : 'ai' # ai | user
}

In [3]:
model = Sequential()
model.add(Conv1D(3, (2), padding='same', input_shape = (config['chances'], 3), activation = 'relu'))
model.add(Flatten())
model.add(Dense(24,activation="relu"))
model.add(Reshape((config['digits'],config['peg_count'])))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 12, 3)             21        
_________________________________________________________________
flatten (Flatten)            (None, 36)                0         
_________________________________________________________________
dense (Dense)                (None, 24)                888       
_________________________________________________________________
reshape (Reshape)            (None, 4, 6)              0         
Total params: 909
Trainable params: 909
Non-trainable params: 0
_________________________________________________________________


In [4]:
state = [[0 for i in range(3)] for j in range(config['chances'])]
state

[[0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0]]

In [5]:
state_to_predict = np.expand_dims(state,0)
state_to_predict

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [24]:
action_prediction = model.predict(state_to_predict)
action_prediction[0]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [25]:
action = 1166
reward = 1
action_as_list = [int(i) for i in str(action)]
action_as_list

[1, 1, 6, 6]

In [26]:
for (i,v) in enumerate(action_as_list):
    action_prediction[0][i][v-1] += reward
action_prediction

array([[[1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1.]]], dtype=float32)